### ISSUE TITLE
Same compounds for different sources

### ISSUE THREAD

**Issue by RicardoMBorges** [NPAtlas/npatlas_website#12]
Hello,
I'm wondering how you deal with situations where the same compounds appear for different sources/organisms.

I'm trying to get all organisms that could be a source for each compound from the downloaded files. The way I'm reading this, we have several compounds listed in the database but each compound has only one source. But I can accept that some compounds are produced by different organisms, right? 

Thank you, 
RIcardo

**Comment by rlinington** [comment]
Hi Ricardo,

This is an old thread, but I'll give you a quick reply. We only include the first instance of discovery from a microbial source in our DB. Therefore if a compound is found first from Bacillus, and later from Streptomyces we do not capture the second source as an option. It would be better to include all instances of discovery, but this would significantly increase the burden on the curation team, so is not currently part of our curation process.
