### ISSUE TITLE
License has expired.

### ISSUE THREAD

**Issue by yuezhiTang** [NPAtlas/npatlas_website#15]
when i want to search compounds using the basic search, the following prompt appears and there is no result I need, i have never used the software mentioned in the prompt,  how can i do?
Molecule export failed:Error: Response is not OK from /webservices2/rest-v1/util/calculate/molExport
HTTP ERROR:
Status code:451
Status text:
Response text:
You don't have appropriate license for: Marvin for JavaScript

**Comment by jvansan** [comment]
Thank you for pointing this out. We are actively working on replacing with
an open source alternative. I will mark this issue as closed when it’s
fixed. Thanks for you patience.

**Comment by jvansan** [comment]
This has now been fixed - thank you again for your patience!
