### ISSUE TITLE
SNAP-MS job running for more than 24 hours

### ISSUE THREAD

**Issue by ShinyBasu** [NPAtlas/npatlas_website#18]
Hello, I am a new user and I started a SNAP-MS job from my newly created account yesterday afternoon. The job status is still 'RUNNING' (well after 24 hours) now. I had used a GNPS Graphml file as the input (Job ID: cd8ea8b9-0823-4c08-a9a0-ad9272cecbb6). I would be very grateful if someone could kindly guide me regarding how to get an output.

Thanks

**Comment by rlinington** [comment]
Hi there, this is probably because you are using an output from GNPS2, which we do not currently support. Please try getting your GNPS output file from GNPS1 using these instructions: 

https://liningtonlab.github.io/snapms_documentation/#graphml
