### ISSUE TITLE
Cluster link directed to NPAID by mistake

### ISSUE THREAD

**Issue by rlinington** [NPAtlas/npatlas_website#2]
On the compound page, clicking the cluster id hyperlink takes you to a cluster containing that NPAID. E.g. if the cluster id is 140 and you click this lunk, it takes you to cluster 126, which contains NPAID 140.

**Comment by rlinington** [comment]
This issue is also present for the Node ID hyperlinks, which direct to the corresponding NPAID by mistake

**Comment by jvansan** [comment]
Is this not the desired behavior? It should go to the correct network and highlight the compound at least for the Cluster page.

For your example, if you go to NPA000140
<img width="576" alt="Screen Shot 2020-08-18 at 3 49 04 PM" src="https://user-images.githubusercontent.com/15289535/90573075-5958db80-e16a-11ea-9e04-44c20428167c.png">

**Comment by jvansan** [comment]
> Is this not the desired behavior? It should go to the correct network and highlight the compound at least for the Cluster page.
> 
> For your example, if you go to NPA000140
> <img alt="Screen Shot 2020-08-18 at 3 49 04 PM" width="576" src="https://user-images.githubusercontent.com/15289535/90573075-5958db80-e16a-11ea-9e04-44c20428167c.png">

Nevermind, it seems the annotation of the Cluster and Node IDs is incorrect somehow.
