### ISSUE TITLE
Forgot password error

### ISSUE THREAD

**Issue by chasemc** [NPAtlas/npatlas_website#3]
I was going to try and fix the record for [NPA005807](https://www.npatlas.org/joomla/index.php/explore/compounds?npaid=NPA005807) (it says it's fungal in origin but as far as I can tell it's eDNA derived, and likely bacterial in origin)

But I'm dumb and forgot my password. When I tried to reset I got the following error:

![image](https://user-images.githubusercontent.com/18691127/94054894-d7c81f00-fda1-11ea-9d20-7a12ed63421d.png)

**Comment by jvansan** [comment]
I have correct this issue. It was a configuration problem after changing the email password.

Thanks @chasemc for reporting! I have also submitted the NP Atlas correction report for you already.
