### ISSUE TITLE
Adding more format options in downloading search results

### ISSUE THREAD

**Issue by Rahulsubbaraj** [NPAtlas/npatlas_website#5]
While using the search option the results are only available in TSV format. Most of the modeling software are demanding SDF format. Kindly add an option to download results in SDF format. Or please help me with an alternate solution.

**Comment by jvansan** [comment]
@Rahulsubbaraj thanks for the suggestions. I agree that this would be a nice feature. At the moment, our infrastructure does not directly suppor thits, therefore it would require a rather significant amount of work. We will certainly add this to our list of desired near term features. In terms of immediate alternative solutions, a relatively simple Python script could be generated to perform this conversion.
