### ISSUE TITLE
Submit button for addition/correction doesn't work 

### ISSUE THREAD

**Issue by bjreisman** [NPAtlas/npatlas_website#7]
Thanks for maintaining this resource. I tried to submit an correction but the submit button doesn't seem to work for me, it doesn't load a new page or seem to respond at all.  I had the same issues on both firefox and microsoft edge. 
The follow boxes were filled in 
1. NPA ID
2. doi
3. Correct compound (tried both SMILES and uploaded chemdraw)
4. Incorrect or other (tried both).

**Comment by jvansan** [comment]
@bjreisman, thanks for reporting the error. We are currently in the process of rebuilding much of the underlying architecture of the NP Atlas and will be sure to address this problem!

In the meantime, if you would like to report any errors please send the appropriate details to
corrections@npatlas.org.
