### ISSUE TITLE
PMIDs in TSV download

### ISSUE THREAD

**Issue by need47** [NPAtlas/npatlas_website#9]
In the downloaded TSV file from: https://www.npatlas.org/download, each PMID has a suffix of '.0'. Not a big deal, but something to improve. Thanks.
![image](https://user-images.githubusercontent.com/1194165/140546481-f3ef9127-c995-4068-b25c-815461e9eaf2.png)

**Comment by jvansan** [comment]
Hello, thanks for filing the issue!

I will make this change to our Download generation tool and upload a new version shortly.

**Comment by jvansan** [comment]
Changes implemented and the download file should now be fixed.

Thanks again for filing this issue!

**Comment by need47** [comment]
Confirmed. Thanks a lot.
